<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="C40FF62PC" name="com.rsi.kma.automation.testScripts.Regression.Remote" tests="2" failures="1" timestamp="19 Dec 2017 05:46:08 GMT" time="0.021" errors="0">
  <testcase name="loginRemote" time="0.009" classname="com.rsi.kma.automation.testScripts.Regression.Remote">
    <skipped/>
  </testcase> <!-- loginRemote -->
  <testcase name="logout" time="0.012" classname="com.rsi.kma.automation.testScripts.Regression.Remote">
    <failure type="java.lang.AssertionError" message="Log out is not present on the Overview activity">
      <![CDATA[java.lang.AssertionError: Log out is not present on the Overview activity
	at org.junit.Assert.fail(Assert.java:88)
	at com.rsi.kma.automation.modules.ActionModule.isDisplayed(ActionModule.java:67)
	at com.rsi.kma.automation.modules.ActionModule.click(ActionModule.java:19)
	at com.rsi.kma.automation.utility.Utils.logout(Utils.java:514)
	at com.rsi.kma.automation.utility.BaseClass.logout(BaseClass.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:212)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- logout -->
</testsuite> <!-- com.rsi.kma.automation.testScripts.Regression.Remote -->
